# Docker Composeのフォーマットバージョンを指定（3.9）
version: '3.9'

services:
  # MySQLコンテナ設定
  mysql:
    image: mysql:8
    container_name: endpoint-sample-mysql
    # エラーでコンテナが落ちた際のみ自動で再起動を行います
    restart: on-failure
    command: --port 3307
    # 環境設定はrootユーザーのみ設定を行います。
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    # 'http://localhost:3307'
    ports:
      - 3307:3307
    volumes:
      # test_dbの作成
      - ./db/sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      # test_dbにarticleテーブルの作成
      - ./db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # phpMyAdminコンテナ設定
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: endpoint-sample-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    # 'http://localhost:4040'
    ports:
      - 4040:80
    # `mysql`が実行された後に`phpmyadmin`実行をします
    depends_on:
      - mysql